default:
  image: docker:latest
  services:
    - docker:dind

docker-build-main:
  stage: build
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - docker pull $CI_REGISTRY_IMAGE/main:latest || true
    - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $CI_REGISTRY_IMAGE/main:latest -t $CI_REGISTRY_IMAGE/main:latest .
    - docker push $CI_REGISTRY_IMAGE/main:latest
  only:
    - main

update-production:
  stage: deploy
  image: curlimages/curl
  script:
    - curl -X POST $PORTAINER
  only:
    - main

docker-build:
  stage: build
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - docker pull $CI_REGISTRY_IMAGE/main:latest || true
    - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $CI_REGISTRY_IMAGE/main:latest -t $CI_REGISTRY_IMAGE/main:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE/main:$CI_COMMIT_SHA
  except:
    - main
