default:
  image: docker:latest
  services:
    - docker:dind
variables:
  DOCKER_TLS_CERTDIR: "/certs"

docker-build-master:
  stage: build    
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login $DOCKER_REGISTRY --username $DOCKER_REGISTRY_USER --password-stdin
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/main" .
    - docker push "$CI_REGISTRY_IMAGE/main"
  only:
    - master

update-production:
  stage: deploy
  image: curlimages/curl
  script:
    - curl -X POST $PORTAINER
  only:
    - master

docker-build:
  stage: build
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login $DOCKER_REGISTRY --username $DOCKER_REGISTRY_USER --password-stdin
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/main:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/main:$CI_COMMIT_REF_SLUG"
  except:
    - master
